{
 "title": "Node.js Kafka",
 "tags": [
  "kafka",
  "nodejs"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Rate of messages produced",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(nodejs_kafka_messages_produced_total[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Rate of messages consumed",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(nodejs_kafka_messages_consumed_total[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Retries total",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(nodejs_kafka_retries_total[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "DLQ total",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(nodejs_kafka_dlq_total[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Handler duration p95",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(nodejs_kafka_handler_duration_ms_bucket[1m])) by (le))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Outbox published",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(nodejs_kafka_outbox_published_total[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}